spring:
  application:
    name: bellafit-propagandas
  
  datasource:
    url: jdbc:postgresql://localhost:5432/bellafit_propagandas
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  servlet:
    context-path: /api

# Configurações de segurança
jwt:
  secret: bellafit-secret-key-2024-change-in-production
  expiration: 86400000 # 24 horas em millisegundos

# Configurações de upload
upload:
  path: ./uploads/
  allowed-types: jpg,jpeg,png,gif,mp4,avi,mov
  max-duration: 60 # segundos para vídeos

# Logging
logging:
  level:
    com.bellafit: DEBUG
    org.springframework.security: DEBUG 